In [1]:
!pip install -U sentence-transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB 2.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.7/7.7 MB 72.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 82.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.0/302.0 kB 35.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 96.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 67.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.0/295.0 kB 24.8 MB/s eta 0:00:00
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125923 sha256=30ba20118fca12317af86c65d84550641b0a512b8b328112b2ad21c5321b01e1
  Stored in directory: /root/.cache/pip/wheels/62/f2/10/1e606fd5f02395388f74e7462910fe851042f97238cbbd902f
Successfully built sentence-transformers


In [4]:
from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer('all-MiniLM-L6-v2')

In [5]:
sentences = ["This framework generates embeddings for each input sequence", "Sentences are apssed as a list of strings"]

embeddings = model.encode(sentences)

for sentence , embedding in zip(sentences, embeddings):
  print("sentence:", sentence)
  print("embeddings:", embedding)
  print("")

sentence: This framework generates embeddings for each input sequence
embeddings: [-9.65600163e-02 -7.20615312e-02 -5.64121120e-02 -6.01226352e-02
  4.42360586e-04  1.28907606e-01 -1.14532523e-02 -4.74794805e-02
  1.49714230e-02 -1.13699958e-01 -2.68931948e-02 -1.14260511e-02
  3.23439911e-02 -1.28672540e-03 -1.31407350e-01  5.59898354e-02
 -2.18560379e-02  6.23204075e-02  1.92180034e-02 -1.10534929e-01
 -5.05476631e-02  6.27297238e-02 -1.09306580e-04 -4.34776656e-02
 -3.06016952e-02 -9.69154388e-03 -2.70343246e-03  4.06417958e-02
  1.05083197e-01 -5.96672995e-03  9.49496776e-02 -1.01490607e-02
  3.87408771e-02  3.45420502e-02 -2.29087509e-02  2.95111593e-02
 -2.29301937e-02 -5.86182326e-02 -8.33820999e-02  4.63819923e-03
 -1.70089807e-02  4.04886529e-03  1.38523746e-02  1.61826611e-02
  4.00126390e-02 -4.29513827e-02 -6.06580339e-02 -4.02429327e-02
 -5.33193350e-02  1.66010801e-02 -1.20498054e-01 -1.30392825e-02
 -4.47301827e-02  6.12908639e-02 -1.45603055e-02 -5.35161756e-02
 -1.4552

**Cosine Similarity**

In [6]:
emb1 = model.encode('I am eating apple')
emb2 = model.encode("I like Fruits")
cos_sim = util.cos_sim(emb1, emb2)
print("Cosine Similarity:", cos_sim)

Cosine Similarity: tensor([[0.5398]])


In [8]:
#cos_sim between all pairs
sentences = [
    "A man is eating fruit.",
    "A man is eating a piece of bread",
    "A man is riding a horse",
    "A women is playing Violin",
    "Two men are camping in the woods",
    "A man is riding a white horse in the open field",
    "A monkey is playing Drums",
    "Someone in a gorilla costume is playing drums",
    "Most people prefer python as there prefered coding language",
    "Bigger python, anacondas are found in the depths of Amazon",
    "Amazon is my dream company to work."
]

#Encoding all sentences
embeddings = model.encode(sentences)

#compute cos_sin bet all pairs
cos_sim = util.cos_sim(embeddings, embeddings)

cos_sim

tensor([[ 1.0000,  0.5742,  0.1563, -0.0611,  0.0272,  0.1278, -0.0066, -0.0286,
         -0.0572,  0.0811, -0.0064],
        [ 0.5742,  1.0000,  0.1383, -0.0816,  0.0093,  0.0532,  0.0386,  0.0032,
         -0.1109, -0.0520, -0.1288],
        [ 0.1563,  0.1383,  1.0000, -0.0333,  0.0605,  0.6488,  0.0786,  0.1493,
         -0.0129, -0.0303, -0.0208],
        [-0.0611, -0.0816, -0.0333,  1.0000, -0.1147, -0.0041,  0.1846,  0.2366,
          0.0874, -0.1115, -0.0616],
        [ 0.0272,  0.0093,  0.0605, -0.1147,  1.0000,  0.1286,  0.0309, -0.0520,
         -0.0128,  0.0608, -0.0584],
        [ 0.1278,  0.0532,  0.6488, -0.0041,  0.1286,  1.0000,  0.0325,  0.0636,
         -0.0160, -0.0418, -0.0681],
        [-0.0066,  0.0386,  0.0786,  0.1846,  0.0309,  0.0325,  1.0000,  0.6640,
          0.0253,  0.1404, -0.0115],
        [-0.0286,  0.0032,  0.1493,  0.2366, -0.0520,  0.0636,  0.6640,  1.0000,
          0.1100,  0.0736, -0.0846],
        [-0.0572, -0.1109, -0.0129,  0.0874, -0.0128, -0

In [9]:
#add all pairs to a list with there cos sim score

all_sentence_combinations = []
for i in range(len(cos_sim)-1):
  for j in range(i+1, len(cos_sim)):
    all_sentence_combinations.append((cos_sim[i][j], i, j))

all_sentence_combinations

[(tensor(0.5742), 0, 1),
 (tensor(0.1563), 0, 2),
 (tensor(-0.0611), 0, 3),
 (tensor(0.0272), 0, 4),
 (tensor(0.1278), 0, 5),
 (tensor(-0.0066), 0, 6),
 (tensor(-0.0286), 0, 7),
 (tensor(-0.0572), 0, 8),
 (tensor(0.0811), 0, 9),
 (tensor(-0.0064), 0, 10),
 (tensor(0.1383), 1, 2),
 (tensor(-0.0816), 1, 3),
 (tensor(0.0093), 1, 4),
 (tensor(0.0532), 1, 5),
 (tensor(0.0386), 1, 6),
 (tensor(0.0032), 1, 7),
 (tensor(-0.1109), 1, 8),
 (tensor(-0.0520), 1, 9),
 (tensor(-0.1288), 1, 10),
 (tensor(-0.0333), 2, 3),
 (tensor(0.0605), 2, 4),
 (tensor(0.6488), 2, 5),
 (tensor(0.0786), 2, 6),
 (tensor(0.1493), 2, 7),
 (tensor(-0.0129), 2, 8),
 (tensor(-0.0303), 2, 9),
 (tensor(-0.0208), 2, 10),
 (tensor(-0.1147), 3, 4),
 (tensor(-0.0041), 3, 5),
 (tensor(0.1846), 3, 6),
 (tensor(0.2366), 3, 7),
 (tensor(0.0874), 3, 8),
 (tensor(-0.1115), 3, 9),
 (tensor(-0.0616), 3, 10),
 (tensor(0.1286), 4, 5),
 (tensor(0.0309), 4, 6),
 (tensor(-0.0520), 4, 7),
 (tensor(-0.0128), 4, 8),
 (tensor(0.0608), 4, 9),
 (

In [10]:
#sort by highest cos similarity
all_senetnece_combinations = sorted(all_sentence_combinations, key =lambda x:x[0], reverse = True)

print("Top 5 most similar pairs:")
for score, i , j in all_sentence_combinations[0:5]:
  print("{} \t {} \t {:.4f}".format(sentences[i], sentences[j], cos_sim[i][j]))

Top 5 most similar pairs:
A man is eating fruit. 	 A man is eating a piece of bread 	 0.5742
A man is eating fruit. 	 A man is riding a horse 	 0.1563
A man is eating fruit. 	 A women is playing Violin 	 -0.0611
A man is eating fruit. 	 Two men are camping in the woods 	 0.0272
A man is eating fruit. 	 A man is riding a white horse in the open field 	 0.1278


**Semantic Search:**

In [11]:
from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer('clips/mfaq')

/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py:380: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [12]:
question = "How many models can I host on HuggingFace?"
answer_1 = "All plans come with unlimited private models and datasets."
answer_2 = "AutoNLP is an automatic way to train and deploy state-of-the-art NLP models, seamlessly integrated with the Hugging Face ecosystem."
answer_3 = "Based on how much training data and model variants are created, we send you a compute cost and payment link - as low as $10 per job."

query_embedding = model.encode(question)
corpus_embeddings = model.encode([answer_1, answer_2, answer_3])

print(util.semantic_search(query_embedding, corpus_embeddings))

[[{'corpus_id': 0, 'score': 0.5507139563560486}, {'corpus_id': 2, 'score': 0.49931788444519043}, {'corpus_id': 1, 'score': 0.4596715271472931}]]


In [13]:
from transformers import pipeline

In [14]:
qa_model = pipeline("question-answering")
question = "How many models can I host on HuggingFace?"
context = "All plans come with unlimited private models and datasets."
qa_model(question = question, context = context)

No model was supplied, defaulted to distilbert-base-cased-distilled-squad and revision 626af31 (https://huggingface.co/distilbert-base-cased-distilled-squad).
Using a pipeline without specifying a model name and revision in production is not recommended.


{'score': 0.7017176747322083, 'start': 20, 'end': 29, 'answer': 'unlimited'}

In [15]:
print(util.semantic_search(query_embedding, corpus_embeddings))

[[{'corpus_id': 0, 'score': 0.5507139563560486}, {'corpus_id': 2, 'score': 0.49931788444519043}, {'corpus_id': 1, 'score': 0.4596715271472931}]]


**Clustering**

In [16]:
from sklearn.cluster import KMeans
import numpy as np

embedder = SentenceTransformer('all-MiniLM-L6-v2')

# Corpus with example sentences
corpus = ['A man is eating food.',
          'A man is eating a piece of bread.',
          'Horse is eating grass.',
          'A man is eating pasta.',
          'A Woman is eating Biryani.',
          'The girl is carrying a baby.',
          'The baby is carried by the woman',
          'A man is riding a horse.',
          'A man is riding a white horse on an enclosed ground.',
          'A monkey is playing drums.',
          'Someone in a gorilla costume is playing a set of drums.',
          'A cheetah is running behind its prey.',
          'A cheetah chases prey on across a field.',
          'The cheetah is chasing a man who is riding the horse.',
          'man and women with their baby are watching cheetah in zoo'
          ]
corpus_embeddings = embedder.encode(corpus)

# Normalize the embeddings to unit length
corpus_embeddings = corpus_embeddings /  np.linalg.norm(corpus_embeddings, axis=1, keepdims=True)

In [17]:
corpus_embeddings[0]

array([ 3.32415812e-02,  4.40606195e-03, -6.27695583e-03,  4.83787246e-02,
       -1.38702288e-01, -3.36174108e-02,  1.01128295e-01, -5.43849319e-02,
       -4.32477780e-02, -3.99411619e-02,  7.78639689e-03, -1.27489548e-02,
       -6.68302551e-02, -1.73865929e-02,  4.74506356e-02, -5.77242523e-02,
        1.01888396e-01, -9.11674462e-04,  8.22614580e-02, -5.03416210e-02,
        6.77303001e-02,  4.08765189e-02, -3.58018577e-02, -1.00682467e-01,
       -6.69350754e-03, -5.31685874e-02,  1.00335181e-01, -5.46135940e-02,
       -2.28481814e-02,  1.38387093e-02,  7.48658627e-02, -6.17880300e-02,
        6.39215931e-02,  1.62387379e-02, -5.32299727e-02, -3.86083759e-02,
        3.15276310e-02, -8.11529681e-02, -3.31432223e-02, -5.38515567e-04,
       -3.96074075e-03, -1.52733810e-02, -9.86418570e-04,  9.57987905e-02,
       -5.42919859e-02,  1.84571594e-02, -1.07143588e-01,  1.38884652e-02,
        3.94072533e-02, -2.69243419e-02, -9.15989429e-02, -1.14195384e-02,
        3.38137113e-02, -

In [19]:
#https://stackoverflow.com/questions/55619176/how-to-cluster-similar-sentences-using-bert

clustering_model = KMeans(n_clusters=4)
clustering_model.fit(corpus_embeddings)
cluster_assignment = clustering_model.labels_
print(cluster_assignment)

[2 2 1 2 2 0 0 1 1 3 3 1 1 1 0]


/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [20]:
clustered_sentences = {}
for sentence_id, cluster_id in enumerate(cluster_assignment):
    if cluster_id not in clustered_sentences:
        clustered_sentences[cluster_id] = []

    clustered_sentences[cluster_id].append(corpus[sentence_id])
clustered_sentences

{2: ['A man is eating food.',
  'A man is eating a piece of bread.',
  'A man is eating pasta.',
  'A Woman is eating Biryani.'],
 1: ['Horse is eating grass.',
  'A man is riding a horse.',
  'A man is riding a white horse on an enclosed ground.',
  'A cheetah is running behind its prey.',
  'A cheetah chases prey on across a field.',
  'The cheetah is chasing a man who is riding the horse.'],
 0: ['The girl is carrying a baby.',
  'The baby is carried by the woman',
  'man and women with their baby are watching cheetah in zoo'],
 3: ['A monkey is playing drums.',
  'Someone in a gorilla costume is playing a set of drums.']}

In [21]:
clustered_sentences = {}
for sentence_id, cluster_id in enumerate(cluster_assignment):
    if cluster_id not in clustered_sentences:
        clustered_sentences[cluster_id] = []

    clustered_sentences[cluster_id].append(corpus[sentence_id])
clustered_sentences

{2: ['A man is eating food.',
  'A man is eating a piece of bread.',
  'A man is eating pasta.',
  'A Woman is eating Biryani.'],
 1: ['Horse is eating grass.',
  'A man is riding a horse.',
  'A man is riding a white horse on an enclosed ground.',
  'A cheetah is running behind its prey.',
  'A cheetah chases prey on across a field.',
  'The cheetah is chasing a man who is riding the horse.'],
 0: ['The girl is carrying a baby.',
  'The baby is carried by the woman',
  'man and women with their baby are watching cheetah in zoo'],
 3: ['A monkey is playing drums.',
  'Someone in a gorilla costume is playing a set of drums.']}